version: '3'
services:
  app:
    build: .
    #  context: .
    #  dockerfile: /home/dhiegolira/Documentos/projects/turing-api/apidockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app